run shfmt

diff --git a/bin/prog/vf b/bin/prog/vf
--- a/bin/prog/vf
+++ b/bin/prog/vf
@@ -8,25 +8,25 @@ files_cmd='find . -type f'
 opts="$FZF_DEFAULT_OPTS"
 
 while getopts 'd:go:h' opt; do
-  case ${opt} in
-    d)
-        dir="${OPTARG}"
-        ;;
-    g)
-        files_cmd='git ls-files --others --cached --exclude-standard'
-        ;;
-    o)
-        opts="$opts ${OPTARG}"
-        ;;
-    h)
-        echo "$(basename "$0") [-g] [-d directory] [fragment]..."
-        exit 0
-        ;;
-    ?)
-      echo "Invalid option: -${OPTARG}."
-      exit 1
-      ;;
-  esac
+	case ${opt} in
+	d)
+		dir="${OPTARG}"
+		;;
+	g)
+		files_cmd='git ls-files --others --cached --exclude-standard'
+		;;
+	o)
+		opts="$opts ${OPTARG}"
+		;;
+	h)
+		echo "$(basename "$0") [-g] [-d directory] [fragment]..."
+		exit 0
+		;;
+	?)
+		echo "Invalid option: -${OPTARG}."
+		exit 1
+		;;
+	esac
 done
 
 shift $((OPTIND - 1))
@@ -35,15 +35,14 @@ cd "$dir"
 
 files=$($files_cmd)
 
-for fragment in "$@"
-do
-    files=$(echo "$files" | grep "$fragment")
+for fragment in "$@"; do
+	files=$(echo "$files" | grep "$fragment")
 done
 
 export FZF_DEFAULT_OPTS="$opts"
 
 selected=$(echo "$files" | sed 's|^./||' | fzf --preview "bat --color=always {}" \
-    --preview-window "~3" \
-    --select-1)
+	--preview-window "~3" \
+	--select-1)
 
 "$EDITOR" "$selected"
diff --git a/bin/sat/sat-base-url b/bin/sat/sat-base-url
--- a/bin/sat/sat-base-url
+++ b/bin/sat/sat-base-url
@@ -3,8 +3,8 @@
 state=$(sat-state-dir)
 
 if [ ! -f "$state/url" ]; then
-    echo 'Error: URL is not configured. Use sat-login command to enter it.' >&2
-    exit 1
+	echo 'Error: URL is not configured. Use sat-login command to enter it.' >&2
+	exit 1
 fi
 
 echo "$(<"$state/url")"
diff --git a/bin/util/menu b/bin/util/menu
--- a/bin/util/menu
+++ b/bin/util/menu
@@ -6,36 +6,36 @@ wm_mode=''
 prompt=''
 
 while getopts 'wp' opt; do
-  case ${opt} in
-    w)
-        wm_mode=1
-        ;;
-    p)
-        prompt=1
-        ;;
-    ?)
-      echo "Invalid option: -${OPTARG}."
-      exit 1
-      ;;
-  esac
+	case ${opt} in
+	w)
+		wm_mode=1
+		;;
+	p)
+		prompt=1
+		;;
+	?)
+		echo "Invalid option: -${OPTARG}."
+		exit 1
+		;;
+	esac
 done
 
 if [ -n "$prompt" ]; then
-    cmd="gum input"
-    # choose -m for prompt
+	cmd="gum input"
+	# choose -m for prompt
 fi
 
 if [ -n "$wm_mode" ]; then
-    if [ "$(uname)" = 'Darwin' ]; then
-        cmd='choose'
-    else
-        cmd='rofi -dmenu'
-    fi
+	if [ "$(uname)" = 'Darwin' ]; then
+		cmd='choose'
+	else
+		cmd='rofi -dmenu'
+	fi
 fi
 
 if [ -n "$prompt" ]; then
-    $cmd
+	$cmd
 else
-    items=$(cat)
-    echo "$items" | $cmd
+	items=$(cat)
+	echo "$items" | $cmd
 fi
diff --git a/bin/util/watch-for-drive b/bin/util/watch-for-drive
--- a/bin/util/watch-for-drive
+++ b/bin/util/watch-for-drive
@@ -7,35 +7,35 @@ count=''
 dev_type="part"
 
 while getopts 'n:d:' opt; do
-  case ${opt} in
-    n) 
-        count="${OPTARG}"
-        ;;
-    d) 
-        dev_type="${OPTARG}"
-        ;;
-    ?)
-      echo "Invalid option: -${OPTARG}."
-      exit 1
-      ;;
-  esac
+	case ${opt} in
+	n)
+		count="${OPTARG}"
+		;;
+	d)
+		dev_type="${OPTARG}"
+		;;
+	?)
+		echo "Invalid option: -${OPTARG}."
+		exit 1
+		;;
+	esac
 done
 
 stdbuf -oL -- udevadm monitor --udev -s block | while read -r -- _ _ event devpath _; do
-    if [ "$event" = add ]; then
-        devname=$(udevadm info -p /sys/"$devpath" | awk -v FS== '/DEVNAME/ {print $2}')
+	if [ "$event" = add ]; then
+		devname=$(udevadm info -p /sys/"$devpath" | awk -v FS== '/DEVNAME/ {print $2}')
 
-        if lsblk -o PATH,TYPE | grep "$dev_type" | grep -q "$devname "; then
-            echo "$devname"
+		if lsblk -o PATH,TYPE | grep "$dev_type" | grep -q "$devname "; then
+			echo "$devname"
 
-            if [ -n "$count" ]; then
-                count=$((count-1))
+			if [ -n "$count" ]; then
+				count=$((count - 1))
 
-                if [ "$count" = 0 ]; then
-                    pkill -P $$ udevadm
-                    exit 0
-                fi
-            fi
-        fi
-    fi
+				if [ "$count" = 0 ]; then
+					pkill -P $$ udevadm
+					exit 0
+				fi
+			fi
+		fi
+	fi
 done
