fix phpactor download script

diff --git a/bin/mac/rebuild-macos-env b/bin/mac/rebuild-macos-env
--- a/bin/mac/rebuild-macos-env
+++ b/bin/mac/rebuild-macos-env
@@ -108,8 +108,16 @@ fn-php() {
     bash -c "$(curl -fsSL https://php.new/install/mac/8.5)"
 
     local bin="$HOME/.local/bin/phpactor"
-    curl -Lo "$bin" https://github.com/phpactor/phpactor/releases/latest/download/phpactor.phar
-    chmod a+x "$bin"
+    local tmp
+
+    tmp="$(mktemp)"
+
+    if curl -fsSLo "$tmp" https://github.com/phpactor/phpactor/releases/latest/download/phpactor.phar; then
+        mv "$tmp" "$bin"
+        chmod a+x "$bin"
+    else
+        echo 'Failed to download phpactor' >&2
+    fi
 }
 
 fn-misc() {
