Completions

diff --git a/base/.local/share/bashly/art/bin/art b/base/.local/share/bashly/art/bin/art
--- a/base/.local/share/bashly/art/bin/art
+++ b/base/.local/share/bashly/art/bin/art
@@ -25,13 +25,14 @@ art_usage() {
   printf "  art --version | -v\n"
   echo
   # :command.usage_commands
-  printf "%s\n" "Projects Commands:"
-  printf "  %s   List all projects\n" "list  "
-  printf "  %s   Create a new project\n" "init  "
-  printf "  %s   Select a project (make link to the main dir)\n" "select"
-  echo
   printf "%s\n" "Commands:"
-  printf "  %s   Scene commands\n" "scene "
+  printf "  %s   Generate bash completions\n" "completions"
+  printf "  %s   Scene commands\n" "scene      "
+  echo
+  printf "%s\n" "Projects Commands:"
+  printf "  %s   List all projects\n" "list       "
+  printf "  %s   Create a new project\n" "init       "
+  printf "  %s   Select a project (make link to the main dir)\n" "select     "
   echo
 
   # :command.long_usage
@@ -59,6 +60,32 @@ art_usage() {
     printf "  %s\n" "ART_PROJECTS_PATH"
     printf "    Folder where the projects are stored\n"
     printf "    %s\n" "Default: $HOME/Videos/Creations"
+    echo
+
+  fi
+}
+
+# :command.usage
+art_completions_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "art completions\n\n"
+    printf "  Generate bash completions\n  Usage: eval \"\$(art completions)\"\n\n"
+  else
+    printf "art completions - Generate bash completions\n\n"
+  fi
+
+  printf "%s\n" "Usage:"
+  printf "  art completions\n"
+  printf "  art completions --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n "$long_usage" ]]; then
+    printf "%s\n" "Options:"
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "--help, -h"
+    printf "    Show this help\n"
     echo
 
   fi
@@ -178,7 +205,7 @@ art_scene_usage() {
   printf "%s\n" "Scenes Commands:"
   printf "  %s   List all scenes\n" "list  "
   printf "  %s   Create a new sciene\n" "create"
-  printf "  %s   Add a source to scene\n" "add   "
+  printf "  %s   Import a source to scene\n" "import"
   printf "  %s   Remove source from scene\n" "rm    "
   echo
 
@@ -259,14 +286,14 @@ art_scene_create_usage() {
 }
 
 # :command.usage
-art_scene_add_usage() {
-  printf "art scene add - Add a source to scene\n\n"
+art_scene_import_usage() {
+  printf "art scene import - Import a source to scene\n\n"
   printf "Alias: a\n"
   echo
 
   printf "%s\n" "Usage:"
-  printf "  art scene add SCENE SUBSCENE SOURCE\n"
-  printf "  art scene add --help | -h\n"
+  printf "  art scene import SCENE SUBSCENE SOURCE\n"
+  printf "  art scene import --help | -h\n"
   echo
 
   # :command.long_usage
@@ -418,10 +445,147 @@ inspect_args() {
 }
 
 # :command.user_lib
-# src/lib/validate_scene_exists.sh
-validate_scene_exists() {
-    scene_name="$1"
-    [ -d "$ART_CURRENT_PATH/Scenes/$scene_name" ] || echo "Scene $scene_name does not exist"
+# src/lib/send_completions.sh
+send_completions() {
+  echo $'# art completion                                           -*- shell-script -*-'
+  echo $''
+  echo $'# This bash completions script was generated by'
+  echo $'# completely (https://github.com/dannyben/completely)'
+  echo $'# Modifying it manually is not recommended'
+  echo $''
+  echo $'_art_completions_filter() {'
+  echo $'  local words="$1"'
+  echo $'  local cur=${COMP_WORDS[COMP_CWORD]}'
+  echo $'  local result=()'
+  echo $''
+  echo $'  if [[ "${cur:0:1}" == "-" ]]; then'
+  echo $'    echo "$words"'
+  echo $''
+  echo $'  else'
+  echo $'    for word in $words; do'
+  echo $'      [[ "${word:0:1}" != "-" ]] && result+=("$word")'
+  echo $'    done'
+  echo $''
+  echo $'    echo "${result[*]}"'
+  echo $''
+  echo $'  fi'
+  echo $'}'
+  echo $''
+  echo $'_art_completions() {'
+  echo $'  local cur=${COMP_WORDS[COMP_CWORD]}'
+  echo $'  local compwords=("${COMP_WORDS[@]:1:$COMP_CWORD-1}")'
+  echo $'  local compline="${compwords[*]}"'
+  echo $''
+  echo $'  case "$compline" in'
+  echo $'    \'scene import\'*)'
+  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_art_completions_filter "--help -h")" -- "$cur")'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'scene create\'*)'
+  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_art_completions_filter "--help -h")" -- "$cur")'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'completions\'*)'
+  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_art_completions_filter "--help -h")" -- "$cur")'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'scene list\'*)'
+  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_art_completions_filter "--help -h")" -- "$cur")'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'s import\'*)'
+  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_art_completions_filter "--help -h")" -- "$cur")'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'s create\'*)'
+  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_art_completions_filter "--help -h")" -- "$cur")'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'scene rm\'*)'
+  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_art_completions_filter "--help -h")" -- "$cur")'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'scene ls\'*)'
+  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_art_completions_filter "--help -h")" -- "$cur")'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'scene a\'*)'
+  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_art_completions_filter "--help -h")" -- "$cur")'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'scene c\'*)'
+  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_art_completions_filter "--help -h")" -- "$cur")'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'scene r\'*)'
+  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_art_completions_filter "--help -h")" -- "$cur")'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'s list\'*)'
+  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_art_completions_filter "--help -h")" -- "$cur")'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'select\'*)'
+  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_art_completions_filter "--help -h")" -- "$cur")'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'scene\'*)'
+  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_art_completions_filter "--help -h a c create import list ls r rm")" -- "$cur")'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'s ls\'*)'
+  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_art_completions_filter "--help -h")" -- "$cur")'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'init\'*)'
+  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_art_completions_filter "--help -h")" -- "$cur")'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'s rm\'*)'
+  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_art_completions_filter "--help -h")" -- "$cur")'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'list\'*)'
+  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_art_completions_filter "--help -h")" -- "$cur")'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'s a\'*)'
+  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_art_completions_filter "--help -h")" -- "$cur")'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'s r\'*)'
+  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_art_completions_filter "--help -h")" -- "$cur")'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'s c\'*)'
+  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_art_completions_filter "--help -h")" -- "$cur")'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'ls\'*)'
+  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_art_completions_filter "--help -h")" -- "$cur")'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'s\'*)'
+  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_art_completions_filter "--help -h a c create import list ls r rm")" -- "$cur")'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'l\'*)'
+  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_art_completions_filter "--help -h")" -- "$cur")'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'i\'*)'
+  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_art_completions_filter "--help -h")" -- "$cur")'
+  echo $'      ;;'
+  echo $''
+  echo $'    *)'
+  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_art_completions_filter "--help --version -h -v completions i init l list ls s scene select")" -- "$cur")'
+  echo $'      ;;'
+  echo $''
+  echo $'  esac'
+  echo $'} &&'
+  echo $'  complete -F _art_completions art'
+  echo $''
+  echo $'# ex: filetype=sh'
 }
 
 # src/lib/validations/validate_file_exists.sh
@@ -429,7 +593,20 @@ validate_file_exists() {
   [[ -f "$1" ]] || echo "must be an existing file"
 }
 
+# src/lib/validations/validate_scene_exists.sh
+validate_scene_exists() {
+    scene_name="$1"
+    [ -d "$ART_CURRENT_PATH/Scenes/$scene_name" ] || echo "Scene $scene_name does not exist"
+}
+
 # :command.command_functions
+# :command.function
+art_completions_command() {
+  # src/commands/completions.sh
+  send_completions
+
+}
+
 # :command.function
 art_list_command() {
   # src/commands/list.sh
@@ -489,8 +666,8 @@ art_scene_create_command() {
 }
 
 # :command.function
-art_scene_add_command() {
-  # src/commands/scene/add.sh
+art_scene_import_command() {
+  # src/commands/scene/import.sh
   scene=${args[scene]}
   subscene=${args[subscene]}
   source=${args[source]}
@@ -561,6 +738,13 @@ parse_requirements() {
   case $action in
     -*) ;;
 
+    completions)
+      action="completions"
+      shift
+      art_completions_parse_requirements "$@"
+      shift $#
+      ;;
+
     list | ls)
       action="list"
       shift
@@ -601,6 +785,50 @@ parse_requirements() {
       ;;
 
   esac
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+}
+
+# :command.parse_requirements
+art_completions_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        art_completions_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="completions"
 
   # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
@@ -821,10 +1049,10 @@ art_scene_parse_requirements() {
       shift $#
       ;;
 
-    add | a)
-      action="add"
+    import | a)
+      action="import"
       shift
-      art_scene_add_parse_requirements "$@"
+      art_scene_import_parse_requirements "$@"
       shift $#
       ;;
 
@@ -973,13 +1201,13 @@ art_scene_create_parse_requirements() {
 }
 
 # :command.parse_requirements
-art_scene_add_parse_requirements() {
+art_scene_import_parse_requirements() {
   # :command.fixed_flags_filter
   while [[ $# -gt 0 ]]; do
     case "${1:-}" in
       --help | -h)
         long_usage=yes
-        art_scene_add_usage
+        art_scene_import_usage
         exit
         ;;
 
@@ -991,7 +1219,7 @@ art_scene_add_parse_requirements() {
   done
 
   # :command.command_filter
-  action="scene add"
+  action="scene import"
 
   # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
@@ -1030,17 +1258,17 @@ art_scene_add_parse_requirements() {
 
   # :command.required_args_filter
   if [[ -z ${args['scene']+x} ]]; then
-    printf "missing required argument: SCENE\nusage: art scene add SCENE SUBSCENE SOURCE\n" >&2
+    printf "missing required argument: SCENE\nusage: art scene import SCENE SUBSCENE SOURCE\n" >&2
 
     exit 1
   fi
   if [[ -z ${args['subscene']+x} ]]; then
-    printf "missing required argument: SUBSCENE\nusage: art scene add SCENE SUBSCENE SOURCE\n" >&2
+    printf "missing required argument: SUBSCENE\nusage: art scene import SCENE SUBSCENE SOURCE\n" >&2
 
     exit 1
   fi
   if [[ -z ${args['source']+x} ]]; then
-    printf "missing required argument: SOURCE\nusage: art scene add SCENE SUBSCENE SOURCE\n" >&2
+    printf "missing required argument: SOURCE\nusage: art scene import SCENE SUBSCENE SOURCE\n" >&2
 
     exit 1
   fi
@@ -1159,13 +1387,14 @@ run() {
   parse_requirements "${input[@]}"
 
   case "$action" in
+    "completions") art_completions_command ;;
     "list") art_list_command ;;
     "init") art_init_command ;;
     "select") art_select_command ;;
     "scene") art_scene_command ;;
     "scene list") art_scene_list_command ;;
     "scene create") art_scene_create_command ;;
-    "scene add") art_scene_add_command ;;
+    "scene import") art_scene_import_command ;;
     "scene rm") art_scene_rm_command ;;
   esac
 }
