Toggl api progress

diff --git a/base/.local/share/scripts/toggl b/base/.local/share/scripts/toggl
--- a/base/.local/share/scripts/toggl
+++ b/base/.local/share/scripts/toggl
@@ -1,9 +1,20 @@
 #!/bin/sh
- 
-workspace_id=$(curl -s \
-    -u "$TOGGL_API_TOKEN":api_token https://api.track.toggl.com/api/v9/me \
-    | jq '.default_workspace_id'
-)
+
+cache="${XDG_CACHE_DIR:-$HOME/.cache}/toggl"
+mkdir -pv "$cache"
+
+if [ -f "$cache/workspace" ]; then
+    workspace_id=$(cat "$cache/workspace")
+else
+    workspace_id=$(curl -su \
+        "$TOGGL_API_TOKEN":api_token https://api.track.toggl.com/api/v9/me \
+        | jq '.default_workspace_id')
+
+    echo "$workspace_id" > "$cache/workspace" 
+
+fi
+
+[ -z "$workspace_id" ] && echo "Failed to get default workspace" && exit 1
 
 project_id=$(curl -s \
     https://api.track.toggl.com/api/v9/workspaces/"$workspace_id"/projects \
@@ -14,11 +25,13 @@ project_id=$(curl -s \
     | awk '{print $1}'
 )
 
+[ -z "$project_id" ] && echo "Cancelled" && exit 1
+
 task_id=$(curl -s \
     https://api.track.toggl.com/api/v9/workspaces/"$workspace_id"/projects/"$project_id"/tasks \
     -H "Content-Type: application/json" \
     -u "$TOGGL_API_TOKEN":api_token \
-    | jq -r 'map((.id | tostring) + "\t" + .name) | .[]' \
+    | jq -r 'sort_by(.id) | reverse | map((.id | tostring) + "\t" + .name + .project_name) | .[]' \
     | fzf -i --delimiter="\t" --with-nth=2 \
     | awk -F'\t' '{print $2}'
 )
